drop table if exists bookmarks;

create table bookmarks(
    id INTEGER primary key generated by default as identity,
    title text not null ,
    url text not null ,
    description text ,
    rating INTEGER
);

insert into bookmarks (title, url, description, rating ) values ('Google','http://google.com','An indie search engine startup',2),  ('Google','http://google.com','An indie search engine startup',2), ('Google','http://google.com','An indie search engine startup',2), ('Google','http://google.com','An indie search engine startup',2), ('Google','http://google.com','An indie search engine startup',5), ('Google','http://google.com','An indie search engine startup',4), ('Google','http://google.com','An indie search engine startup',1), ('Google','http://google.com','An indie search engine startup',3), ('Google','http://google.com','An indie search engine startup',5), ('Google','http://google.com','An indie search engine startup',5), ('Google','http://google.com','An indie search engine startup',5)